[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
dotnet = "10.0.202"
"dotnet:csharp-ls" = "0.24.0"
node = "25.9.0"
"pipx:simonw/llm" = "0.30"
python = "3.14.4"
rust = "1.95.0"
uv = "0.11.7"

[tools."pipx:ansible-core"]
uvx = true
uvx_args = "--with botocore --with boto3"
version = "2.20.5"

[tools."pipx:devpi-server"]
version = "6.19.3"
uvx = true
uvx_args = "--with devpi-web"

[tools."pipx:devpi-client"]
version = "7.2.1"
uvx = true
