[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
dotnet = "10.0.201"
"dotnet:csharp-ls" = "0.23.0"
node = "25.9.0"
"pipx:eblume/mole" = "1.0.2"
"pipx:simonw/llm" = "0.30"
python = "3.14.4"
rust = "1.94.1"
uv = "0.11.6"
"pipx:borgmatic" = "2.1.4"

[tools."pipx:ansible-core"]
uvx = true
uvx_args = "--with botocore --with boto3"
version = "2.20.4"

[tools."pipx:devpi-server"]
version = "6.19.3"
uvx = true
uvx_args = "--with devpi-web"

[tools."pipx:devpi-client"]
version = "7.2.1"
uvx = true
