-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm'

return {
    -- Theme
    color_scheme = "myTheme",

    -- Scrollback
    scrollback_lines = 10000,

    -- Not sure why, but Im getting lots of errors.
    warn_about_missing_glyphs = false,

    -- Window
    window_padding = {
      left = 10,
      right = 10,
      top = 10,
      bottom = 10,
    },

    -- Font
    font_size = 18.0,
    font = wezterm.font_with_fallback({
      { family = "VictorMono Nerd Font" },
      { family = "Arial" },
    }),

    -- Tab Bar
    hide_tab_bar_if_only_one_tab = true,
    window_frame = {
      font_size = 16.0,
    },

    colors = {
      tab_bar = {
        active_tab = {
          bg_color = '#1D2122',
          fg_color = '#bdae93',
        },
      },
    },

    -- Disable audio
    audible_bell = "Disabled",

    keys = {
      -- sends completion string for fish autosuggestions
      {
        key = 'Enter',
        mods = 'SHIFT',
        action = wezterm.action.SendString '\x1F'
      },
      -- ctrl-shift-h was "hide"
      {
        key = 'H',
        mods = 'SHIFT|CTRL',
        action = wezterm.action.DisableDefaultAssignment
      },
      -- alt-enter was "fullscreen"
      {
        key = 'Enter',
        mods = 'ALT',
        action = wezterm.action.DisableDefaultAssignment
      },
      -- make super-f "fullscreen"
      {
        key = 'f',
        mods = 'SUPER',
        action = wezterm.action.ToggleFullScreen
      },
      -- super-t open new tab in new dir
      {
        key = 't',
        mods = 'SUPER',
        action = wezterm.action.SpawnCommandInNewTab {
          cwd = wezterm.home_dir,
        },
      },
      -- shift-super-t open new tab in same dir
      {
        key = 't',
        mods = 'SUPER|SHIFT',
        action = wezterm.action.SpawnTab 'CurrentPaneDomain'
      },
    },
}

