[[profiles]]
name = 'sisyphus'
provider = 'Okta'
username = 'erich.blume@illumio.com'
url = 'https://illumio.okta.com/home/amazon_aws/0oaeu6p2qkfL1btN52p6/272?fromHome=true'

[[profiles]]
name = 'abovenet'
provider = 'Okta'
username = 'erich.blume@illumio.com'
url = 'https://illumio.okta.com/home/amazon_aws/0oacq3rdt5bGmacQv2p6/272?fromHome=true'

[[profiles]]
name = 'illumio'
provider = 'Okta'
username = 'erich.blume@illumio.com'
url = 'https://illumio.okta.com/home/amazon_aws/0oaeu500cYTSwxuMT2p6/272?fromHome=true'

[[profiles]]
name = 'illumio-gov-prod'
provider = 'Okta'
username = 'erich.blume@illumio.com'
url = 'https://illumio.okta.com/home/amazon_aws/0oaakw9dxc5QqBpMK2p7/272?fromHome=true'
