---
username: eblume
email: erich.blume@illumio.com
code: $HOME/code/work
environments:
  dev:
    ssh_key: $HOME/.ssh/id_ed25519
    chef_key: $HOME/.ilodevops/eblume.pem
  prod:
    ssh_key: $HOME/.ssh/id_ed25519
    chef_key: $HOME/.ilodevops/eblume.pem
  gov:
    ssh_key: $HOME/.ssh/id_ed25519
    chef_key: $HOME/.ilodevops/eblume.pem
